repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [pre-commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [pre-commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [pre-commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        require_serial: true

      # - id: pytest
      #   name: pytest
      #   stages: [pre-commit]
      #   language: system
      #   entry: pipenv run pytest
      #   types: [python]
      #   pass_filenames: false
