DROP TABLE IF EXISTS track_queue;
DROP TABLE IF EXISTS aliases;
CREATE TABLE track_queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  track_id TEXT NOT NULL,
  status TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE aliases (
  alias TEXT NOT NULL,
  artist TEXT NOT NULL,
  PRIMARY KEY (alias)
);
